name: Build Yami

on:
  push:
    branches: [ "master", "main", "dev" ]
  pull_request:
    branches: [ "master", "main", "dev" ]
  schedule:
    # every day at 7 pm
    - cron:  "0 19 * * *"
  workflow_dispatch:

concurrency: yami

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - name: allow ci scripts
      run: chmod 777 ci/*.sh
    - name: write api config for smoke test
      run: |
        cat << EOF > resources/api_config.json
        {
          "token":  "${{ secrets.DISCORDTOKEN }}",
          "twitchClient": "${{ secrets.TWITCHTOKEN }}",
          "youtubeClient": "${{ secrets.YOUTUBECLIENT }}"
        }
        EOF
    - name: create temp files
      run: |
        mkdir logs
        touch logs/log.txt
        mkdir resources/commands
        touch resources/commands/custom.json
        cat << EOF > resources/commands/custom.json
        []
        EOF
    - name: build typescript
      run: make compile
    - name: run tests
      run: make check
    - name: Build and run the image
      run: ./ci/build_and_run.sh
    - name: Run smoke test
      run: ./ci/smoke_test.sh
