name: Build Yami

on:
  push:
    branches: [ "master", "main", "dev" ]
  pull_request:
    branches: [ "master", "main", "dev" ]
  schedule:
    # every day at 7 pm
    - cron:  "0 19 * * * "

concurrency: yami

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker-practice/actions-setup-docker@master
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - name: build typescript
      run: make compile
    - name: run tests
      run: make check
    - name: Build the Docker image
			run: docker build -t yami_bot .
		- name: Run Image
			run: docker run -d yami_bot
		- name: Smoke Test
			run: ./ci/smoke_test.sh