name: Build Yami

on:
  push:
    branches: [ "master", "main", "dev" ]
  pull_request:
    branches: [ "master", "main", "dev" ]

concurrency: yami

jobs:

  build:
		name: "Run build, check, docker"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker-practice/actions-setup-docker@master
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - name: build typescript
      run: make compile
    - name: run tests
      run: make check
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yami_bot:$(date +%s)
